[package]
name = "laser-tetris-common"
version = "0.1.0"
authors = ["arfrie22 <43021241+arfrie22@users.noreply.github.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[lib]
crate-type = ["lib"]


[dependencies]