[package]
name = "demo"
version = "0.1.0"
edition = "2021"

[dependencies]
pixels = { version = "0.14.0", features = []}
env_logger = "0.10"
error-iter = "0.4"
log = "0.4"
winit = { version = "0.29", features = ["rwh_05"] }
winit_input_helper = "0.15"
rand = "0.8.5"
tetris = { path = "../tetris" }
